{% set version = "0.30.0" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 4798889d82bfde548dd6684dffcfd56f9c5d87aaa5c10c53bcd3d534dc2f2fd1

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - metakernel >=0.21.2
    - jupyter_client >=4.3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.21.2
    - jupyter_client >=4.3.0
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
