{% set version = "0.36.0" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 925882f8915c86ed75b6db8e1341deed980dba0be73bf07365d3ea08961a1ddb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - jupyter-packaging >=0.9,<2
    - metakernel >=0.24.0
    - jupyter_client >=4.3.0
    - ipykernel
    - hatchling >=1.0

  run:
    - python >={{ python_min }}
    - metakernel >=0.24.0
    - jupyter_client >=4.3.0
    - ipykernel

test:
  requires:
    - python {{ python_min }}
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Jupyter kernel for Octave.
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
