{% set version = "0.20.0" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  fn: octave_kernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 7d797267aa726488cbaf3d2e7903697cc3b41e459d7fe555a28e07a9bf5270a0

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - metakernel >=0.17.4
    - jupyter_client >=4.3
    - ipykernel

  run:
    - python
    - metakernel >=0.17.4
    - jupyter_client >=4.3
    - ipykernel

test:
  # Python imports
  imports:
    - octave_kernel
    - octave_kernel.install

about:
  home: http://github.com/calsto/octave_kernel
  license: BSD
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD


extra:
    recipe-maintainers:
        - blink1073
