{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 8c9821bf32dde6b3aae9b09c5663e035f0987530245257c7d31e3fcf0086195f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - metakernel >=1.0.6
    - jupyter_client >=8.1.0
    - ipykernel >=6.22.0
    - hatchling >=1.5

  run:
    - python >={{ python_min }}
    - metakernel >=1.0.6
    - jupyter_client >=8.1.0
    - ipykernel >=6.22.0
    - rpds-py >=2026.5.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - octave_kernel
  commands:
    - pip check

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Jupyter kernel for Octave.
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
