{% set version = "0.30.3" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: d179f6ca56190fd14254c41e13a80a68f16a541408eaf909c66d491695d285ce

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - metakernel >=0.23.0
    - jupyter_client >=4.3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.23.0
    - jupyter_client >=4.3.0
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  summary: 'A Jupyter kernel for Octave.'
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
