{% set version = "1.0.2" %}
{% set python_min = "3.11" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: e51b806989ed5ce9889c789440ed818351fe584e094ca053de79c2ac2eb4162b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - metakernel >=1.0
    - jupyter_client >=8.1.0
    - ipykernel >=6.22.0
    - hatchling >=1.5

  run:
    - python >={{ python_min }}
    - metakernel >=1.0.0
    - jupyter_client >=8.1.0
    - ipykernel >=6.22.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Jupyter kernel for Octave.
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
