{% set version = "0.31.1" %}

package:
  name: octave_kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/octave_kernel/octave_kernel-{{ version }}.tar.gz
  sha256: 6b52c3c024f1f516012bf17c0e51265dd0175cd854e2011a29d359629d79f0ba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - metakernel >=0.24.0
    - jupyter_client >=4.3.0
    - ipykernel

  run:
    - python
    - metakernel >=0.24.0
    - jupyter_client >=4.3.0
    - ipykernel

test:
  imports:
    - octave_kernel

about:
  home: https://github.com/Calysto/octave_kernel
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: A Jupyter kernel for Octave.
  license_family: BSD

extra:
  recipe-maintainers:
    - blink1073
    - ocefpaf
