travis:
  secure:
    BINSTAR_TOKEN: vO2XC8iZHxzN7X6syfa9zaFpFIJHauNjJ7dvVpTsUBpqNTzZidzXYCCPa5nNt/9QeVY8QCzEqntaXTE9rouhQHZefavU1s4dv0FqF7Keu9bDErn3h++TXUhVIOxZCGEfTbTvQ8nanOyZVzzBzeoPF/VnLbXLFGJ55RtCaAd4TXqiT0KFEeN6ttwU9plfnhy/4Qx3w8WjlO4LT8hcsLZxg1OSYClA3ndC0uy/1XYr0444MOdLvpdviEmBtG1MtgtHgod8WgERsytT8S5HsM/PHcbweByNV6GtwySrsxZGL0OmYmtx+qHaNjhZuhz0h1OT5So/okAr1EHVUWVosmhCh3+IukW0eOaLhFWCy58Ux69bWv7Qu+5BhnmR9/X9hCCAzuQumzya017juKtfnR2vrh+/38L0HQQGMFy7B1kSaJD7anUcNjzO2IgHw46BLRYrHRAhwZzgvvmIzG7LGulDZyVT3INvCbKb4Ccya9rp+a2lKQ8Tn5759kJJqf/YRPMPYOcu+AaFz2imGp3mgnNxvf3SBNwGEhzlL9ebZrMgmwGVf99ZMTO7X3glqssDm9MIParf8EjWO9mnDuCXEcTZPwuCNndpt2Sv5iZ17rlwN6qFazqY89PD6zH35NmB51luJBdMNh66OF8PMRbt4eRJqqm26DHUIIur5nza/LPtOK4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
